version: "2"

services:
  # example web target
  demo-target:
    image: nginx:alpine
    ports:
      - "8090:80"
    environment:
      - NGINX_HOST=demo-target
      - NGINX_PORT=80
  # swerve
  swerve:
    build:
      context: .
    image: axelspringer/swerve
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    environment:
      - SWERVE_HTTP=:8080
      - SWERVE_HTTPS=:8081
      - SWERVE_API=:8082
      - SWERVE_DB_REGION=eu-central-1
      - SWERVE_DB_ENDPOINT=http://dynamodb:8000
      - SWERVE_DB_KEY=0
      - SWERVE_DB_SECRET=0
      - SWERVE_BOOTSTRAP=0
      - SWERVE_API_CLIENT_STATIC=/tmp/static
      - SWERVE_DOMAINS=Domains
      - SWERVE_DOMAINS_TLS_CACHE=DomainsTLSCache
    volumes:
      - ./bin/swerve_linux:/swerve
      - ./src/client/dist:/tmp/static
    depends_on:
      - "init-dynamodb"
    links:
      - "dynamodb"
  # local dynamodb
  dynamodb:
    image: dwmkerr/dynamodb:latest
    command: "-sharedDb -dbPath /data"
    restart: always
    volumes:
      - dynamo_local:/data
    ports:
      - "8000:8000"
  # inititalize the database
  init-dynamodb:
    image: garland/aws-cli-docker
    command: "/bin/sh /tmp/init_db.sh"
    volumes:
      - ./scripts/dynamodb/init.sh:/tmp/init_db.sh 
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1
    depends_on:
      - "dynamodb"
    links:
      - "dynamodb"
volumes:
  dynamo_local: