version: "2"

services:
  # local CA (letsencrypt)
  pebble:
    image: letsencrypt/pebble
    restart: always
    ports:
    - "14000:14000"
    - "15000:15000"
    environment:
      - PEBBLE_VA_ALWAYS_VALID=1
  # dynamodb
  dynamodb:
    image: dwmkerr/dynamodb:latest
    command: "-sharedDb -dbPath /data"
    restart: always
    volumes:
      - dynamo_local:/data
    ports:
      - "8000:8000"
  # inititalize  the database
  init-dynamodb:
    image: garland/aws-cli-docker
    command: "/bin/sh /tmp/init_db.sh"
    volumes:
      - ./scripts/init_dynamo.sh:/tmp/init_db.sh 
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-west-1
      - TABLE_REDIRECTS=Redirects
      - TABLE_CERTCACHE=CertCache
      - TABLE_USERS=Users
    depends_on:
      - "dynamodb"
    links:
      - "dynamodb"
volumes:
  dynamo_local: